version: '3'
name: mathbot
services:
  mathbot:
    image: golang:1.23
    entrypoint: bash -c "go install -buildvcs=false ./cmd/mathbot && ./bin/mathbot"
    working_dir: /mathbot
    ports:
      - 8085:8085
    volumes:
      - ..:/mathbot
    environment:
      GOPATH: /mathbot
      GO111MODULE: auto
      CONFIG_PATH: ./configs/local.yaml

networks:
  default:
    name: local-network
    external: true